=== erotourtes/qUAckzak/schemas/quackhat.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
  <xs:simpleType name="nonEmptyString">
    <xs:restriction base="xs:string">
      <xs:minLength value="1" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="identifier">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-z0-9][a-z0-9_-]*" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="layer">
    <xs:restriction base="xs:string">
      <xs:enumeration value="inherit" />
      <xs:enumeration value="behind" />
      <xs:enumeration value="front" />
      <xs:enumeration value="foreground" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="facing">
    <xs:restriction base="xs:string">
      <xs:enumeration value="inherit" />
      <xs:enumeration value="movement" />
      <xs:enumeration value="fixed" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="controller">
    <xs:restriction base="xs:string">
      <xs:enumeration value="attached" />
      <xs:enumeration value="flying_follower" />
      <xs:enumeration value="ground_follower" />
      <xs:enumeration value="world_one_shot" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="trigger">
    <xs:restriction base="xs:string">
      <xs:enumeration value="default" />
      <xs:enumeration value="idle" />
      <xs:enumeration value="running" />
      <xs:enumeration value="airborne" />
      <xs:enumeration value="crouching" />
      <xs:enumeration value="sliding" />
      <xs:enumeration value="ragdoll" />
      <xs:enumeration value="netted" />
      <xs:enumeration value="direction_changed" />
      <xs:enumeration value="death" />
      <xs:enumeration value="follower_moving" />
      <xs:enumeration value="follower_idle" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="stateTrigger">
    <xs:restriction base="trigger">
      <xs:enumeration value="default" />
      <xs:enumeration value="idle" />
      <xs:enumeration value="running" />
      <xs:enumeration value="airborne" />
      <xs:enumeration value="crouching" />
      <xs:enumeration value="sliding" />
      <xs:enumeration value="ragdoll" />
      <xs:enumeration value="netted" />
      <xs:enumeration value="follower_moving" />
      <xs:enumeration value="follower_idle" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="cadence">
    <xs:restriction base="xs:string">
      <xs:enumeration value="time" />
      <xs:enumeration value="distance" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="animationType">
    <xs:attribute name="trigger" type="trigger" use="required" />
    <xs:attribute name="firstFrame" type="xs:nonNegativeInteger" use="required" />
    <xs:attribute name="lastFrame" type="xs:nonNegativeInteger" use="required" />
    <xs:attribute name="ticksPerFrame" type="xs:positiveInteger" use="required" />
  </xs:complexType>

  <xs:complexType name="emitterType">
    <xs:attribute name="condition" type="stateTrigger" use="required" />
    <xs:attribute name="cadence" type="cadence" use="required" />
    <xs:attribute name="minimumInterval" type="xs:positiveInteger" use="required" />
    <xs:attribute name="maximumInterval" type="xs:positiveInteger" use="required" />
  </xs:complexType>

  <xs:complexType name="componentType">
    <xs:sequence>
      <xs:element name="animation" type="animationType" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="emitter" type="emitterType" minOccurs="0" />
    </xs:sequence>
    <xs:attribute name="id" type="identifier" use="required" />
    <xs:attribute name="sprite" type="nonEmptyString" use="required" />
    <xs:attribute name="frameWidth" type="xs:positiveInteger" />
    <xs:attribute name="frameHeight" type="xs:positiveInteger" />
    <xs:attribute name="parent" type="identifier" default="duck" />
    <xs:attribute name="offsetX" type="xs:decimal" default="0" />
    <xs:attribute name="offsetY" type="xs:decimal" default="0" />
    <xs:attribute name="layer" type="layer" default="front" />
    <xs:attribute name="facing" type="facing" default="inherit" />
    <xs:attribute name="controller" type="controller" default="attached" />
    <xs:attribute name="speed" type="xs:decimal" />
    <xs:attribute name="group" type="identifier" />
  </xs:complexType>

  <xs:element name="hat">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="component" type="componentType" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="name" type="nonEmptyString" use="required" />
      <xs:attribute name="preview" type="nonEmptyString" default="preview.png" />
      <xs:attribute name="image" type="nonEmptyString" default="hat.png" />
    </xs:complexType>
    <xs:unique name="uniqueComponentId">
      <xs:selector xpath="component" />
      <xs:field xpath="@id" />
    </xs:unique>
  </xs:element>
</xs:schema>

=== erotourtes/qUAckzak/content/quackhat/cossack/hat.xml
<?xml version="1.0" encoding="utf-8"?>
<hat xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="../../../schemas/quackhat.xsd"
     name="qUAckzak Cossack">
  <component id="moustache"
             sprite="components/moustache.png"
             frameWidth="48"
             frameHeight="24"
             offsetX="3"
             offsetY="-2"
             layer="foreground">
    <animation trigger="default"
               firstFrame="0"
               lastFrame="3"
               ticksPerFrame="5" />
  </component>
  <component id="hair"
             sprite="components/hair.png"
             frameWidth="32"
             frameHeight="48"
             offsetX="4"
             offsetY="-10"
             layer="behind">
    <animation trigger="default"
               firstFrame="0"
               lastFrame="3"
               ticksPerFrame="5" />
    <animation trigger="airborne"
               firstFrame="4"
               lastFrame="7"
               ticksPerFrame="3" />
  </component>

  <component id="windmill"
             sprite="components/pets/windmill.png"
             offsetX="-28"
             offsetY="-12"
             facing="movement"
             controller="flying_follower"
             speed="2"
             group="pets" />
  <component id="windmill-wings"
             sprite="components/pets/windmill-wings.png"
             frameWidth="48"
             frameHeight="48"
             parent="windmill"
             layer="inherit">
    <animation trigger="default"
               firstFrame="0"
               lastFrame="3"
               ticksPerFrame="3" />
  </component>

  <component id="sharovary"
             sprite="components/pets/sharovary.png"
             frameWidth="48"
             frameHeight="48"
             offsetX="-28"
             offsetY="8"
             facing="movement"
             controller="ground_follower"
             speed="2"
             group="pets">
    <animation trigger="follower_moving"
               firstFrame="0"
               lastFrame="1"
               ticksPerFrame="4" />
    <animation trigger="follower_idle"
               firstFrame="2"
               lastFrame="3"
               ticksPerFrame="5" />
  </component>

  <component id="cannon"
             sprite="components/pets/cannon.png"
             offsetX="-30"
             offsetY="8"
             facing="movement"
             controller="ground_follower"
             speed="1.5"
             group="pets" />

  <component id="chaika"
             sprite="components/pets/chaika.png"
             offsetX="-32"
             offsetY="6"
             facing="movement"
             controller="flying_follower"
             speed="1.5"
             group="pets" />

  <component id="barrel"
             sprite="components/pets/barrel.png"
             frameWidth="48"
             frameHeight="48"
             offsetX="-28"
             offsetY="8"
             facing="fixed"
             controller="ground_follower"
             speed="2"
             group="pets">
    <animation trigger="follower_moving"
               firstFrame="0"
               lastFrame="3"
               ticksPerFrame="3" />
    <animation trigger="follower_idle"
               firstFrame="0"
               lastFrame="0"
               ticksPerFrame="1" />
  </component>

  <component id="pipe"
             sprite="components/decorations/pipe.png"
             offsetX="6"
             offsetY="-2" />

  <component id="vyshyvanka"
             sprite="components/decorations/vyshyvanka.png"
             frameWidth="48"
             frameHeight="48"
             offsetY="5">
    <animation trigger="default"
               firstFrame="0"
               lastFrame="0"
               ticksPerFrame="1" />
    <animation trigger="running"
               firstFrame="1"
               lastFrame="3"
               ticksPerFrame="3" />
  </component>

  <component id="bandura"
             sprite="components/decorations/bandura.png"
             offsetX="-5"
             offsetY="3"
             layer="behind" />

  <component id="banner"
             sprite="components/decorations/banner.png"
             frameWidth="48"
             frameHeight="64"
             offsetX="-12"
             offsetY="-12"
             layer="behind">
    <animation trigger="default"
               firstFrame="0"
               lastFrame="3"
               ticksPerFrame="4" />
  </component>

  <component id="saber"
             sprite="components/decorations/saber.png"
             offsetX="8"
             offsetY="4" />

  <component id="sunflower"
             sprite="components/effects/sunflower.png"
             frameWidth="24"
             frameHeight="24"
             offsetY="10"
             layer="behind"
             facing="fixed">
    <animation trigger="default"
               firstFrame="0"
               lastFrame="3"
               ticksPerFrame="4" />
    <emitter condition="running"
             cadence="distance"
             minimumInterval="8"
             maximumInterval="16" />
  </component>

  <component id="pipe-smoke"
             sprite="components/effects/pipe-smoke.png"
             frameWidth="16"
             frameHeight="16"
             parent="pipe"
             offsetY="-3">
    <animation trigger="default"
               firstFrame="0"
               lastFrame="3"
               ticksPerFrame="4" />
    <emitter condition="default"
             cadence="time"
             minimumInterval="30"
             maximumInterval="60" />
  </component>

  <component id="spirit"
             sprite="components/effects/spirit.png"
             frameWidth="32"
             frameHeight="48"
             offsetY="-8"
             layer="foreground"
             controller="world_one_shot">
    <animation trigger="death"
               firstFrame="0"
               lastFrame="3"
               ticksPerFrame="5" />
  </component>

  <component id="saber-glint"
             sprite="components/effects/saber-glint.png"
             frameWidth="16"
             frameHeight="16"
             parent="saber"
             offsetX="4"
             offsetY="-5"
             layer="foreground">
    <animation trigger="direction_changed"
               firstFrame="0"
               lastFrame="3"
               ticksPerFrame="3" />
  </component>

  <component id="death-animation"
             sprite="components/effects/death-animation.png"
             frameWidth="48"
             frameHeight="48"
             layer="foreground"
             controller="world_one_shot">
    <animation trigger="death"
               firstFrame="0"
               lastFrame="3"
               ticksPerFrame="4" />
    <animation trigger="death"
               firstFrame="4"
               lastFrame="7"
               ticksPerFrame="4" />
    <animation trigger="death"
               firstFrame="8"
               lastFrame="11"
               ticksPerFrame="4" />
  </component>
</hat>
